### ISSUE TITLE
calvin_pick_server shouldn't depend on muffin_msgs

### ISSUE THREAD

**Issue by mintar** [uos/calvin_robot#12]
See title. First of all, `muffin_msgs` isn't even on GitHub yet, so now people outside UOS can't even build `calvin_robot` any more. Second, MUFFIN should depend on Calvin, not the other way around.

My suggestion would be to create a new package (`calvin_msgs`) and move `muffin_msgs/PickServer.action` there. Also maybe we could rename it to `Pick.action` or something ("PickServer" isn't a verb).

**Comment by mintar** [comment]
@v4hn @hdeeken @jspricke Any thoughts?

@v4hn Could you take care of this, since you moved `calvin_pick_server` here?

**Comment by v4hn** [comment]
Argh, sorry for that,

I missed the muffin_msgs-dependency when I catkinized the module...

I just renamed the action to PickAndStore and moved it into a newly
created calvin_msgs module. Any further complains? :-)

**Comment by mintar** [comment]
Perfect!
